fint:
  application-id: fint-kontroll-role-factory
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}
    producer-max-message-size: 3145728
    consumer-max-message-size: 5242880
    consumer-partition-fetch-bytes: 3145728
  kontroll:
    role:
      publishing:
        initial-delay: 90000
        fixed-delay: 180000
      edu-publishing:
        initial-delay: 60000
        fixed-delay: 180000
    aggregated-role:
      publishing:
        initial-delay: 120000
        fixed-delay: 180000
    member:
      publishing:


spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
  producer:
    max:
      request:
        size: 2097152
  profiles:
    include:
      - observability

springwolf:
  docket:
    base-package: no.fintlabs
    info:
      title: ${fint.application-id}
      version: 1.0.0
      description: FINT Kontroll Role Factory
    servers:
        kafka-server:
            protocol: kafka

logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    no.fintlabs.cache.ehcache.FintEhCacheEventLogger: WARN
    io.github.springwolf: DEBUG