fint:
  org-id: fintlabs.no
  client:
    base-url: https://beta.felleskomponent.no
  kafka:
    default-replicas: 1
  kontroll:
    role:
      publishing:
        initial-delay: 5000
        fixed-delay: 180000
      edu-publishing:
        initial-delay: 15000
        fixed-delay: 180000
    aggregated-role:
      publishing:
        initial-delay: 10000
        fixed-delay: 180000
novari:
  kafka:
    default-replicas: 1
    topic:
      org-id: fintlabs-no
      domain-context: kontroll
    application-id: ${fint.application-id}

spring:
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8098
logging:
  level:
    no.fintlabs.role.RolePublishingComponent: DEBUG