fint:
  application-id: fint-kontroll-role-factory
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}
    producer-max-message-size: 3145728
    consumer-max-message-size: 5242880
    consumer-partition-fetch-bytes: 3145728
  kontroll:
    role:
      publishing:
        initial-delay: 100000
        fixed-delay: 1800000
      edu-publishing:
        initial-delay: 30000
        fixed-delay: 180000
    aggregated-role:
      publishing:
        initial-delay: 20000
        fixed-delay: 180000
    member:
      publishing:


spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
  producer:
    max:
      request:
        size: 2097152
  profiles:
    include:
      - observability

logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    no.fintlabs: DEBUG
    no.fintlabs.cache.ehcache.FintEhCacheEventLogger: WARN