fint:
  org-id: fintlabs.no
  flyt:
    resource-gateway:
      authorization:
        enable: true
  client:
    base-url: https://beta.felleskomponent.no
  kafka:
    default-replicas: 1
  kontroll:
    role:
      publishing:
        initial-delay: 20000
        fixed-delay: 150000
spring:
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8098
logging:
  level:
    no.fintlabs.role.RolePublishingComponent: DEBUG