apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-role-factory
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-role-factory:latest
  imagePullPolicy: Always
  env:
    - name: fint.client.base-url
      value: 'https://api.felleskomponent.no'
    - name: spring.kafka.consumer.group-id
      value: 'fint-kontroll-role-factory'
    - name: JAVA_TOOL_OPTIONS
      value: "-XX:+ExitOnOutOfMemoryError -Xmx896m -verbose:gc"
    - name: 'fint.kontroll.member.days-before-arbeidsforhold-start'
      value: '0'
    - name: 'fint.kontroll.member.days-before-elevforhold-start'
      value: '0'
    - name: 'fint.kontroll.member.days-before-undervisningsgruppemedlemskap-start'
      value: '0'
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
