apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-role-factory
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-role-factory:latest
  imagePullPolicy: Always
  env:
    - name: fint.client.base-url
      value: 'https://api.felleskomponent.no'
    - name: spring.kafka.consumer.group-id
      value: 'fint-kontroll-role-factory'
    - name: fint.kontroll.role.edu-publishing.cron
      value: "0 0/3 * * * ?"
    - name: fint.kontroll.member.days-before-start-student
      value: '0'
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
